### ISSUE TITLE
Failed to AWSMobileClient.getCredentials

### ISSUE THREAD

**Issue by ihdream72** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#18]
Hi~

I think I did well according to the guide.
I can actually verify user authentication in aws-cognito-console.

but when i try to connect (press start maste/viewer in 2 mobile phone)
after "Signaling connect" Toast message, Phone screen was changed  2-camera view.
But Local-View only displayed, Remote-View has back screen

I think this problem cause by fail to getCredentials() so can not create AWSKinesisVideoClient.

- Test Phone : Galaxy Note9/10 - Android 10

Can you check my AWSConfiguration.Json File ?

{
  "Version": "1.0",
  "CredentialsProvider": {
    "CognitoIdentity": {
      "Default": {
        "PoolId": "us-east-2:4456b8ff-f34e-485b-86b1-51e40721042a",
        "Region": "us-east-2"
      }
    }
  },
  "IdentityManager": {
    "Default": {}
  },
  "CognitoUserPool": {
    "Default": {
      "AppClientSecret": "19s114knmsciqln526njnm5ukg513jgkpc0p4rf4jq3ub3cou7o4",
      "AppClientId": "5e9ok6hk6tb2sq9suk1ot66r3f",
      "PoolId": "us-east-2_pebqk18EH",
      "Region": "us-east-2"
    }
  }
}
   
Please Help me~~

2020-03-06 15:36:41.712 28370-28535/com.amazonaws.kinesisvideo.webrtc.demoapp.minsdk24 W/AWSMobileClient: Could not check if ACCESS_NETWORK_STATE permission is available.
    java.lang.ClassNotFoundException: android.support.v4.content.ContextCompat
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at com.amazonaws.mobile.client.AWSMobileClient.isNetworkAvailable(AWSMobileClient.java:751)
        at com.amazonaws.mobile.client.AWSMobileClient.getUserStateDetails(AWSMobileClient.java:963)
        at com.amazonaws.mobile.client.AWSMobileClient.waitForSignIn(AWSMobileClient.java:903)
        at com.amazonaws.mobile.client.AWSMobileClient.getCredentials(AWSMobileClient.java:355)
        at com.amazonaws.kinesisvideo.demoapp.fragment.StreamWebRtcConfigurationFragment.getAwsKinesisVideoClient(StreamWebRtcConfigurationFragment.java:272)
        at com.amazonaws.kinesisvideo.demoapp.fragment.StreamWebRtcConfigurationFragment.access$300(StreamWebRtcConfigurationFragment.java:53)
        at com.amazonaws.kinesisvideo.demoapp.fragment.StreamWebRtcConfigurationFragment$UpdateSignalingChannelInfoTask.doInBackground(StreamWebRtcConfigurationFragment.java:315)
        at com.amazonaws.kinesisvideo.demoapp.fragment.StreamWebRtcConfigurationFragment$UpdateSignalingChannelInfoTask.doInBackground(StreamWebRtcConfigurationFragment.java:301)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by ihdream72** [comment]
I think it was firewall issue
