### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by debugapp** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#4]
2019-12-18 15:45:38.544 27220-27245/com.amazonaws.kinesisvideo.webrtc.demoapp.minsdk24 E/AndroidRuntime: FATAL EXCEPTION: Thread-3
    Process: com.amazonaws.kinesisvideo.webrtc.demoapp.minsdk24, PID: 27220
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/amazonaws/mobile/auth/ui/SignInActivity;
        at com.amazonaws.mobile.auth.ui.SignInUI.presentAuthUI(SignInUI.java:109)
        at com.amazonaws.mobile.auth.ui.SignInUI.loginWithBuilder(SignInUI.java:128)
        at com.amazonaws.mobile.auth.ui.SignInUI.access$400(SignInUI.java:36)
        at com.amazonaws.mobile.auth.ui.SignInUI$LoginBuilder.execute(SignInUI.java:181)
        at com.amazonaws.mobile.client.AWSMobileClient$26.run(AWSMobileClient.java:2975)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:762)
     Caused by: java.lang.ClassNotFoundException: com.amazonaws.mobile.auth.ui.SignInActivity
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.amazonaws.mobile.auth.ui.SignInUI.presentAuthUI(SignInUI.java:109) 
        at com.amazonaws.mobile.auth.ui.SignInUI.loginWithBuilder(SignInUI.java:128) 
        at com.amazonaws.mobile.auth.ui.SignInUI.access$400(SignInUI.java:36) 
        at com.amazonaws.mobile.auth.ui.SignInUI$LoginBuilder.execute(SignInUI.java:181) 
        at com.amazonaws.mobile.client.AWSMobileClient$26.run(AWSMobileClient.java:2975) 
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101) 
        at java.lang.Thread.run(Thread.java:762) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/app/AppCompatActivity;
        at com.amazonaws.mobile.auth.ui.SignInUI.presentAuthUI(SignInUI.java:109) 
        at com.amazonaws.mobile.auth.ui.SignInUI.loginWithBuilder(SignInUI.java:128) 
        at com.amazonaws.mobile.auth.ui.SignInUI.access$400(SignInUI.java:36) 
        at com.amazonaws.mobile.auth.ui.SignInUI$LoginBuilder.execute(SignInUI.java:181) 
        at com.amazonaws.mobile.client.AWSMobileClient$26.run(AWSMobileClient.java:2975) 
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101) 
        at java.lang.Thread.run(Thread.java:762) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.app.AppCompatActivity" on path: DexPathList[[zip file "/data/app/com.amazonaws.kinesisvideo.webrtc.demoapp.minsdk24-2/base.apk"],nativeLibraryDirectories=[/data/app/com.amazonaws.kinesisvideo.webrtc.demoapp.minsdk24-2/lib/arm64, /data/app/com.amazonaws.kinesisvideo.webrtc.demoapp.minsdk24-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.amazonaws.mobile.auth.ui.SignInUI.presentAuthUI(SignInUI.java:109) 
        at com.amazonaws.mobile.auth.ui.SignInUI.loginWithBuilder(SignInUI.java:128) 
        at com.amazonaws.mobile.auth.ui.SignInUI.access$400(SignInUI.java:36) 
        at com.amazonaws.mobile.auth.ui.SignInUI$LoginBuilder.execute(SignInUI.java:181) 
        at com.amazonaws.mobile.client.AWSMobileClient$26.run(AWSMobileClient.java:2975) 
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101) 
        at java.lang.Thread.run(Thread.java:762)

**Comment by zhiyua-git** [comment]
Hi @debugapp , can you kindly provide these information? 
1. Your Android device
2. Your Android OS version
3. Your DemoApp commit
4. Is it failing after you set up the awsconfiguration.json with Cognito information or failing after you reopen the app sometime after you successfully launched the app?

**Comment by zhiyua-git** [comment]
The fix is in, please pull it down and have a try. Thanks for reporting the issue.

**Comment by debugapp** [comment]
Thanks , I alreay fixed that problem after updating code。
Galaxy s6, android 7.0。
